name: 🚀 Release

on:
  release:
    types: [ released ]

jobs:
  release:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v3

      -   name: Generate plugin artifact
          run: |
            zip -r "${GITHUB_WORKSPACE}/release.zip" builds/

      -   name: Upload release asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ${{ github.workspace }}/release.zip
            asset_name: impress.zip
            asset_content_type: application/zip
